In [1]:
import numpy as np

In [12]:
# zeros : used to create matrix with values = 0

t1 = np.zeros((5), dtype = np.int32)
print('t1 is 1D')
print(t1)
print()
t2 = np.zeros((3,3), dtype = np.int32)
print('t2 is 2D')
print(t2)
print()
t3 = np.zeros((3,3,3), dtype = np.int32)
print('t3 is 3D')
print(t3)

t1 is 1D
[0 0 0 0 0]

t2 is 2D
[[0 0 0]
 [0 0 0]
 [0 0 0]]

t3 is 3D
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [16]:
t4 = np.zeros((2,2,3), dtype = np.int32)
print('t4 is 3D')
print(t4)

t4 is 3D
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [20]:
# ones : used to create matrix with values = 1

t1 = np.ones((5), dtype = np.int32)
print('t1 is 1D')
print(t1)
print()
t2 = np.ones((3,3), dtype = np.int32)
print('t2 is 2D')
print(t2)
print()
t3 = np.ones((3,3,3), dtype = np.int32)
print('t3 is 3D')
print(t3)

t1 is 1D
[1 1 1 1 1]

t2 is 2D
[[1 1 1]
 [1 1 1]
 [1 1 1]]

t3 is 3D
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [30]:
# eye : used to create identity matrix

t = np.eye((4), dtype=np.int32)
print(t)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [34]:
# empty : used to generate random value but they are tending towards 0

tt = np.empty(5)
print(tt)

[0.00000000e+000 1.06689884e-311 1.06689884e-311 1.06689884e-311
 0.00000000e+000]


In [40]:
# arange : used to create array with specified evenly spaced values within given interval

ar = np.arange(1,11,5)
print(ar)
print()
a2 = np.arange(1,100,2)
print(a2)

[1 6]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [43]:
# linspace : Creates an array with a specified number of evenly spaced values over a given interval.

v, d = np.linspace(1, 10, 5, retstep = True)
print('Array :',  v)
print('diff :', d) 

Array : [ 1.    3.25  5.5   7.75 10.  ]
diff : 2.25


In [46]:
# random.rand : creates array with random values between 0 to 1

r = np.random.rand(5)
print(r)

[0.11690351 0.97138803 0.44849202 0.41963952 0.6999922 ]


In [2]:
r2 = np.random.randint(44,48)
print(r2)

47


In [3]:
a1 = np.array([10,3,5,6])
print(a1.ndim)
print(a1.shape)
print(a1.dtype)
print(a1.size)

1
(4,)
int64
4


In [4]:
# copy(arr) : used to copy a array into another

a1 = np.array([10,3,5,6])
a2 = np.copy(a1)
print(a2)

[10  3  5  6]


In [17]:
a1 = np.array([10,3,5,6,11])

print(a1)
a2 = np.copy(a1)
print(a2)



a1[2]=500
print(a2)
print(a1)

[10  3  5  6 11]
[10  3  5  6 11]
[10  3  5  6 11]
[ 10   3 500   6  11]


In [14]:
# view : 
a = np.array([10,3,5,6])
print(a)
v = a1.view()
print(v)

a[1] = 312
print(v)
print(id(a))
print(id(v))

[10  3  5  6]
[ 10 312   5   6]
[ 10 312   5   6]
2597490711920
2597490707696


In [8]:
# reshape : can create/update array of higher dimension

aa  = np.array([10,20,30,40,50,60])
print(aa)

d2 = aa.reshape(2,3)
print(d2)
print()
d3 = aa.reshape(2,1,3)
print(d3)
print()
print()
print()
d4 = aa.reshape(3,2,1)
print(d4)

[10 20 30 40 50 60]
[[10 20 30]
 [40 50 60]]

[[[10 20 30]]

 [[40 50 60]]]



[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]
