In [1]:
import numpy as np

In [6]:
n = np.array([[1,2,3],[4,5,6]])
np.savetxt("mar23.txt", n, delimiter = ': ', fmt='%d', header = "first file", footer = "end of code", comments = "# ")

In [3]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
np.save('mfile', b)
print('data saved')

[[1 2 3]
 [4 5 6]]
data saved


In [4]:
k = np.load('mfile.npy')
print(k)

[[1 2 3]
 [4 5 6]]
