In [2]:
import numpy as np

In [8]:
# SCALAR ARRAY
t = np.array(8)
print(t)
print(t.ndim)
print(t.shape)
print(t.dtype)


8
0
()
int64


In [3]:
# 1-D/VECTOR ARRAY
l = np.array([1,2,3,4,5,6])
print(l)
print(l.ndim)
print(l.shape)
print(l.dtype)
print(l.size)

[1 2 3 4 5 6]
1
(6,)
int64
6


In [5]:
# 2-D/MATRIX ARRAY 
v = np.array(( [1,2,3] , [4,5,6] ))
print(v)
print(v.ndim)
print(v.dtype)
print(v.shape)

[[1 2 3]
 [4 5 6]]
2
int64
(2, 3)


In [10]:
# 3-D/TENSOR ARRAY
p = np.array([[ [1,2,3] , [4,5,6] ], [ [7,8,9], [6,5,4] ], [ [7,4,1], [9,6,3] ] ])
print(p)
print(p.ndim)
print(p.dtype)
print(p.shape)
print(p[2,1,2])
print(p[2,1])
print(p[2])

[[[1 2 3]
  [4 None 6]]

 [[7 8 9]
  [6 5 4]]

 [[7 4 1]
  [9 6 3]]]
3
object
(3, 2, 3)
3
[9 6 3]
[[7 4 1]
 [9 6 3]]


In [5]:
a = 12
print(id(a))
a = 133
print(id(a))

140711506310616
140711506314488


In [6]:
a = np.array('s')
print(a.dtype)

<U1


In [8]:
p = np.array([ [1,2,3,4,5], [10,20,30,40,50], [100,200,300,400,500] ])
print(p[1,3:5])
print(p[2,2])

[40 50]
300


In [16]:
d3 = np.array([1,2,3], ndmin = 4)
print(d3)
print(d3.ndim)

[[[[1 2 3]]]]
4


In [26]:
d3 = np.array( [[1,2,3], [1,2,3]], ndmin = 4)
print(d3)
print(d3.shape)
print(d3.ndim)

[[[[1 2 3]
   [1 2 3]]]]
(1, 1, 2, 3)
4


In [3]:
# nditer : used to iterate the array

p = np.array([[ [1,2,3] , [4,5,6] ], [ [7,8,9], [6,5,4] ], [ [7,4,1], [9,6,3] ] ])
for i in  p:
    print(i)
for i in np.nditer(p):
    print(i)

[[1 2 3]
 [4 5 6]]
[[7 8 9]
 [6 5 4]]
[[7 4 1]
 [9 6 3]]
1
2
3
4
5
6
7
8
9
6
5
4
7
4
1
9
6
3


In [31]:
# ndenumerate : used to iterate array with its index

p = np.array([[ [1,2,3] , [4,5,6] ], [ [7,8,9], [6,5,4] ], [ [7,4,1], [9,6,3] ] ])
for i in np.ndenumerate(p):
    print(i)

((0, 0, 0), np.int64(1))
((0, 0, 1), np.int64(2))
((0, 0, 2), np.int64(3))
((0, 1, 0), np.int64(4))
((0, 1, 1), np.int64(5))
((0, 1, 2), np.int64(6))
((1, 0, 0), np.int64(7))
((1, 0, 1), np.int64(8))
((1, 0, 2), np.int64(9))
((1, 1, 0), np.int64(6))
((1, 1, 1), np.int64(5))
((1, 1, 2), np.int64(4))
((2, 0, 0), np.int64(7))
((2, 0, 1), np.int64(4))
((2, 0, 2), np.int64(1))
((2, 1, 0), np.int64(9))
((2, 1, 1), np.int64(6))
((2, 1, 2), np.int64(3))


In [35]:
p = np.array([[ [1,2,3] , [4,5,6] ], [ [7,8,9], [6,5,4] ], [ [7,4,1], [9,6,3] ] ])
for i, v in np.ndenumerate(p):
    print('index :', i, 'value :', v)

index : (0, 0, 0) value : 1
index : (0, 0, 1) value : 2
index : (0, 0, 2) value : 3
index : (0, 1, 0) value : 4
index : (0, 1, 1) value : 5
index : (0, 1, 2) value : 6
index : (1, 0, 0) value : 7
index : (1, 0, 1) value : 8
index : (1, 0, 2) value : 9
index : (1, 1, 0) value : 6
index : (1, 1, 1) value : 5
index : (1, 1, 2) value : 4
index : (2, 0, 0) value : 7
index : (2, 0, 1) value : 4
index : (2, 0, 2) value : 1
index : (2, 1, 0) value : 9
index : (2, 1, 1) value : 6
index : (2, 1, 2) value : 3


In [6]:
a = np.array([1,2,3,4,5])
k = np.array_split(a, 3)
print(k)
a1 = np.array(k[0])
print(a1)

[array([1, 2]), array([3, 4]), array([5])]
[1 2]


In [8]:
p = np.array([[ [1,2,3] , [4,5,6] ], [ [7,8,9], [6,5,4] ], [ [7,4,1], [9,6,3] ] ])
a = np.array_split(p, 4)
print(a)

[array([[[1, 2, 3],
        [4, 5, 6]]]), array([[[7, 8, 9],
        [6, 5, 4]]]), array([[[7, 4, 1],
        [9, 6, 3]]]), array([], shape=(0, 2, 3), dtype=int64)]


In [11]:
v = np.array([ [1,2,3] , [4,5,6] ])
a = np.array_split(v,4)
print(a)
b = a[1]
c = b[0]
d = np.array(c[0])
print(d)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int64), array([], shape=(0, 3), dtype=int64)]
4


In [4]:
a1 = [1,2,3,4,5]
a2 = [6,7,8,9,10]
a3 = [11,12,13,14,15]

In [8]:
# hstack : horizontal stacking of array
d1 = np.hstack((a1, a2))
print(d1)

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
# vstack : vertical stacking of array
d2 = np.vstack((a1, a2, a3))
print(d2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
# dstack : stacks array 1 on 1 into 3d array
d3 = np.dstack((a2,a3))
print(d3)

[[[ 6 11]
  [ 7 12]
  [ 8 13]
  [ 9 14]
  [10 15]]]


In [22]:
# transpose : transpose of matrix
print(d2)
print(d2.shape)
a = np.transpose(d2)
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
(5, 3)


In [24]:
# delete : delete a set value from array

a1 = np.array([10,20,30,40,50])
np.delete(a1,2)

array([10, 20, 40, 50])

In [27]:
a1 = np.array([10,20,30,40,50])
a1 = np.delete(a1,2)
print(a1)

[10 20 40 50]


In [29]:
a1 = np.array([10,20,30,40,50])
np.delete(a1, np.where(a1 == 50))

array([10, 20, 30, 40])

In [31]:
a1 = np.array([10,20,30,40,50])
np.delete(a1, np.where(a1 < 20))

array([20, 30, 40, 50])

In [4]:
# intersect

a1 = np.array([1,2,3,4,5])
a2 = np.array([6,2,8,4,10])
a3 = np.intersect1d(a1,a2)
print(a3)

[2 4]


In [5]:
# union 
a4 = np.union1d(a1,a2)
a4

array([ 1,  2,  3,  4,  5,  6,  8, 10])

In [2]:
# unique
a = np.array([10, 10, 20, 45, 23, 45])
np.unique(a)

array([10, 20, 23, 45])