In [1]:
import numpy as np

In [3]:
# 1
n = int(input("Enter size: "))
a = np.ones((n, n), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

Enter size:  10


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [5]:
# 2
a = np.array([2,3,0,1,0,9])
s = []
for i in range(len(a)):
    if a[i] == 0:
        s.append(i)
print(s)

[2, 4]


In [5]:
# 3
a = np.zeros(10)
a[5] = 9
print(a)

[0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]


In [6]:
# 4
a = np.ones((3,3), dtype= bool)
print(a)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [12]:
# 5
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print('first row :',a[0])
print('last column :', a[:,3])

first row : [1 2 3 4]
last column : [ 4  8 12 16]


In [18]:
# 6
a = np.array([1,45,5,12,52,485,6312,4,5,5,13])
x = np.sort(a)[::-1]
print(x)

[6312  485   52   45   13   12    5    5    5    4    1]


In [2]:
# 7
a = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
x = np.sort(a[1])
print(x)

[12 22 82]


In [7]:
# 8
a = np.array([34, 43, 73, 82, 22, 12, 53, 94, 66])
for i in range(len(a)):
    if a[i] % 2 != 0:
        a[i] = -1
print(a)

[34 -1 -1 82 22 12 -1 94 66]


In [2]:
# 9
a = np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [10]:
# 10
a1 = np.array([1,2,3,4,5])
a2 = np.array([1,4,7,8,5])
a3 = np.union1d(a1,a2) 
a4 = np.intersect1d(a1,a2)
a = np.setdiff1d(a3,a4)
print(a)

[2 3 7 8]


In [2]:
# 11
a1=np.array([1,2,3,4,5])
a2=np.array([1,7,8,4,5])
a=[]
for i in range(len(a1)):
    for j in range(len(a2)):
        if i == j:
            if a1[i] == a2[j]:
                a.append(i)
arr = np.array(a)
print(arr)

[0 3 4]


In [3]:
# 12
a=np.array([[1,2,3,4,5],[0,8,7,9,6]])
print('max:',np.max(a1))
print('min:',np.min(a1))

max: 9
min: 0


In [6]:
# 13
a = np.array([[1,2,3,4,5],[0,8,7,9,6]])
x = np.delete(a1, 2, axis= 1)
print(x)

[[1 2 4 5]
 [0 8 9 6]]


In [2]:
# 14
a = np.array([1,2,3,4,5,6,7,8,9])
a1 = np.split(a,3)
print(a1)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [7]:
# 15
a = np.array([[34, None, 73], [82, 22, 12], [53, 94, None]])
count = 0
for i in a:
    for j in i:
        if j == None:
            count += 1
print(count)
            

2
