In [1]:
import numpy as np

In [8]:
A2= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(A2)
print(A2[1,1:4])       ## [7,8,9]
print(A2[0:2,4])       ## [5,10]
print(A2[0:2,1:4])     ## [2,3,4][7,8,9]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]
[ 5 10]
[[2 3 4]
 [7 8 9]]


In [3]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[2:5])         ## [2,3,4]

[2 3 4]


In [4]:
a = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(a[:2,:2])       ## [0,1][3,4]

[[0 1]
 [3 4]]


In [5]:
a = np.array([[1, 3, 5, 7],[9, 11, 13, 15]])
print(a[:2,:2])       ## [1,3][9,11]

[[ 1  3]
 [ 9 11]]


In [6]:
a = np.array([[1, 3, 5, 7],
[9, 11, 13, 15],
[2, 4, 6, 8]])
print(a[:2,:2])       ## [1,3][9,11]

[[ 1  3]
 [ 9 11]]


In [4]:
a = np.array([[1, 3, 5, 7],
[9, 11, 13, 15],
[2, 4, 6, 8]])
print(a[1:3,2:4])     ## [13,15],[6,8]

[[13 15]
 [ 6  8]]


In [12]:
# Get the positions where elements of array a and b match

a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 4, 3, 7, 8])

for i in range(len(a)):
    for j in range(len(b)):
        if i == j:
            if a[i] == b[j]:
                print(i, a[i], b[j])

0 1 1
2 3 3
5 7 7


In [16]:
a = np.array([ [0,1,2,3],
            [4,5,6,7],
            [8,9,10,11],
            [12,13,14,15] ])
print(a[0:2, 0:2])          ## [0,1][4,5]
print(a[2:0,2:0])           ## []
print(a[2:0:-1,2:0:-1])     ## [10,9][6,5]

[[0 1]
 [4 5]]
[]
[[10  9]
 [ 6  5]]


In [2]:
a = np.array([10,20,30,40,50,60,70,80,90])
b = np.array([ [0,1,2,3],
            [4,5,6,7],
            [8,9,10,11],
            [12,13,14,15] ])
print(b[0:2,1:3])     ## [1,2][5,6]
print(a[2:6:3])       ## [30,50] 
print(a[-1:-3])       ## [90,60,30]
print(b[::-1])        ## reverse of b
print(b[::3, 2:])     ## [2,3][14,15]

[[1 2]
 [5 6]]
[30 60]
[]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[ 2  3]
 [14 15]]


In [7]:
# Write a program to convert 1D array into 2D array with 3 rows.
X=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = np.reshape(X, (3,4))
print(x, x.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4)


In [ ]:
d = np.array([10,20,30,40,50,60,70])
print(d[-4:])       ## [30,40,50,60,70]

In [4]:
a = np.array([ [1,3,5,7],[9,11,13,15] ])
print(a[:2,1:2])

[[ 3]
 [11]]
